feat: add command exist check

diff --git a/local/bin/check-brew-cask-upgrade b/local/bin/check-brew-cask-upgrade
--- a/local/bin/check-brew-cask-upgrade
+++ b/local/bin/check-brew-cask-upgrade
@@ -3,10 +3,14 @@
 #set -x
 #set -e
 
-if ! [ -x "$(command -v ggrep)" ]; then
-	echo 'Error: Required GNU grep, try brew install grep'
-	exit 1;
-fi
+check_command_installed () {
+	NAME=$1
+	BREW_NAME=$2
+	if ! [ -x "$(command -v $NAME)" ]; then
+		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+		exit 1;
+	fi
+}
 
 get_version_by_info () {
 	local __cask=$1
@@ -20,6 +24,10 @@ get_version_by_cat () {
 	local __latest=$(cat /usr/local/Homebrew/Library/Taps/homebrew/*/Casks/$__cask.rb | ggrep -Po "version '\K.+(?=')" | sort -r --version-sort | head -n 1)
 	echo $__latest
 }
+
+if [ `uname` = 'Darwin' ]; then
+	check_command_installed ggrep grep
+fi
 
 for CASK in `ls /usr/local/Caskroom `; do
 	#LATEST="$(get_version_by_info $CASK)"
diff --git a/local/bin/generate-output-summary-md b/local/bin/generate-output-summary-md
--- a/local/bin/generate-output-summary-md
+++ b/local/bin/generate-output-summary-md
@@ -1,5 +1,18 @@
 #!/bin/bash
 
+check_command_installed () {
+	NAME=$1
+	BREW_NAME=$2
+	if ! [ -x "$(command -v $NAME)" ]; then
+		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+		exit 1;
+	fi
+}
+
+if [ `uname` = 'Darwin' ]; then
+	check_command_installed gsed gnu-sed
+fi
+
 mkdir -p .output
 echo -n '' > .output/summary.md
 # ls *.md | sed 's/.md//g' | grep -v summary | awk '{print "- ["$0"]("$0")"}' 
diff --git a/local/bin/remark b/local/bin/remark
--- a/local/bin/remark
+++ b/local/bin/remark
@@ -21,6 +21,19 @@ fi
 
 OUTPUT_FILE_NAME=$FILE_NAME.remark.generated.html
 
+check_command_installed () {
+	NAME=$1
+	BREW_NAME=$2
+	if ! [ -x "$(command -v $NAME)" ]; then
+		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+		exit 1;
+	fi
+}
+
+if [ `uname` = 'Darwin' ]; then
+	check_command_installed gsed gnu-sed
+fi
+
 cat > $OUTPUT_FILE_NAME << EOF
 <!DOCTYPE html>
 <html>
diff --git a/local/bin/tinypng b/local/bin/tinypng
--- a/local/bin/tinypng
+++ b/local/bin/tinypng
@@ -2,13 +2,24 @@
 
 FILE_NAME=$1
 
+export http_proxy=http://127.0.0.1:1235
+export https_proxy=http://127.0.0.1:1235
+
+check_command_installed () {
+	NAME=$1
+	BREW_NAME=$2
+	if ! [ -x "$(command -v $NAME)" ]; then
+		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+		exit 1;
+	fi
+}
+
 if [ -z $FILE_NAME ]; then
 	echo "Useage: tinypng filename"
 	exit 0;
 fi
+check_command_installed jq jq
 
-export http_proxy=http://127.0.0.1:1235
-export https_proxy=http://127.0.0.1:1235
 
 cp $FILE_NAME ${FILE_NAME}.bak
 URL=$(curl --user api:${TINYPNG_API_SECRECT} --data-binary @$FILE_NAME https://api.tinify.com/shrink | jq -r '.output.url')
