style: format

diff --git a/local/bin/generate-output-summary-md b/local/bin/generate-output-summary-md
--- a/local/bin/generate-output-summary-md
+++ b/local/bin/generate-output-summary-md
@@ -1,26 +1,26 @@
 #!/bin/bash
 
-check_command_installed () {
-	NAME=$1
-	BREW_NAME=$2
-	if ! [ -x "$(command -v $NAME)" ]; then
-		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
-		exit 1;
-	fi
+check_command_installed() {
+  NAME=$1
+  BREW_NAME=$2
+  if ! [ -x "$(command -v $NAME)" ]; then
+    echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+    exit 1
+  fi
 }
 
-if [ `uname` = 'Darwin' ]; then
-	check_command_installed gsed gnu-sed
+if [ $(uname) = 'Darwin' ]; then
+  check_command_installed gsed gnu-sed
 fi
 
 mkdir -p .output
-echo -n '' > .output/summary.md
-# ls *.md | sed 's/.md//g' | grep -v summary | awk '{print "- ["$0"]("$0")"}' 
+echo -n '' >.output/summary.md
+# ls *.md | sed 's/.md//g' | grep -v summary | awk '{print "- ["$0"]("$0")"}'
 
 for file in $(gfind . -name "*.md" -printf "%T+\t%p\n" | awk '{print $2}' | gsed 's/^\.\///g' | grep -v .output | grep -v summary.md | gsort -h); do
-	TITLE=$(cat $file | grep -m 1 '^# ' | awk -F '#' '{gsub(/[ \t]+$/, "", $2);gsub(/^[ \t]+/, "", $2); print $2}')
-	NAME=$(echo $file | sed 's/.md//g' | awk -F '/' '{print $NF}')
-	echo "- [$TITLE]($NAME)" >> .output/summary.md
+  TITLE=$(cat $file | grep -m 1 '^# ' | awk -F '#' '{gsub(/[ \t]+$/, "", $2);gsub(/^[ \t]+/, "", $2); print $2}')
+  NAME=$(echo $file | sed 's/.md//g' | awk -F '/' '{print $NF}')
+  echo "- [$TITLE]($NAME)" >>.output/summary.md
 done
 
 # vim: set ft=sh:
diff --git a/local/bin/homebrew-using-mirror b/local/bin/homebrew-using-mirror
--- a/local/bin/homebrew-using-mirror
+++ b/local/bin/homebrew-using-mirror
@@ -4,32 +4,35 @@ set -e
 
 mirror=$1
 
-check_command_installed () {
-	name=$1
-	brew_name=$2
-	if ! [ -x "$(command -v $name)" ]; then
-		echo "Error: Required GNU $name, try \`brew install $brew_name\`"
-		exit 1;
-	fi
+check_command_installed() {
+  name=$1
+  brew_name=$2
+  if ! [ -x "$(command -v $name)" ]; then
+    echo "Error: Required GNU $name, try \`brew install $brew_name\`"
+    exit 1
+  fi
 }
 
 if [ -z "$mirror" ]; then
-	echo "Useage: homebrew-using-mirror mirror"
-	echo "mirror example: https://mirrors.tuna.tsinghua.edu.cn/git/"
-	echo "default example: https://github.com/"
-	exit 0;
+  echo "Useage: homebrew-using-mirror mirror"
+  echo "mirror example: https://mirrors.tuna.tsinghua.edu.cn/git/"
+  echo "default example: https://github.com/"
+  exit 0
 fi
 check_command_installed brew brew
 
-BREW_TAPS="$(BREW_TAPS="$(brew tap 2>/dev/null)"; echo -n "${BREW_TAPS//$'\n'/:}")"
+BREW_TAPS="$(
+  BREW_TAPS="$(brew tap 2>/dev/null)"
+  echo -n "${BREW_TAPS//$'\n'/:}"
+)"
 for tap in core cask{,-fonts,-drivers,-versions} command-not-found; do
-    if [[ ":${BREW_TAPS}:" == *":homebrew/${tap}:"* ]]; then
-        # 将已有 tap 的上游设置为本镜像并设置 auto update
-        # 注：原 auto update 只针对托管在 GitHub 上的上游有效
-        git -C "$(brew --repo homebrew/${tap})" remote set-url origin "${mirror}homebrew/homebrew-${tap}.git"
-        git -C "$(brew --repo homebrew/${tap})" config homebrew.forceautoupdate true
-    else   # 在 tap 缺失时自动安装（如不需要请删除此行和下面一行）
-        # brew tap --force-auto-update "homebrew/${tap}" "${mirror}/homebrew/homebrew-${tap}.git"
-        echo -n ''
-    fi
+  if [[ ":${BREW_TAPS}:" == *":homebrew/${tap}:"* ]]; then
+    # 将已有 tap 的上游设置为本镜像并设置 auto update
+    # 注：原 auto update 只针对托管在 GitHub 上的上游有效
+    git -C "$(brew --repo homebrew/${tap})" remote set-url origin "${mirror}homebrew/homebrew-${tap}.git"
+    git -C "$(brew --repo homebrew/${tap})" config homebrew.forceautoupdate true
+  else # 在 tap 缺失时自动安装（如不需要请删除此行和下面一行）
+    # brew tap --force-auto-update "homebrew/${tap}" "${mirror}/homebrew/homebrew-${tap}.git"
+    echo -n ''
+  fi
 done
diff --git a/local/bin/qrdecode b/local/bin/qrdecode
--- a/local/bin/qrdecode
+++ b/local/bin/qrdecode
@@ -2,17 +2,16 @@
 
 set -e
 
-check_command_installed () {
-	name=$1
-	brew_name=$2
-	if ! [ -x "$(command -v $name)" ]; then
-		echo "Error: Required GNU $name, try \`brew install $brew_name\`"
-		exit 1;
-	fi
+check_command_installed() {
+  name=$1
+  brew_name=$2
+  if ! [ -x "$(command -v $name)" ]; then
+    echo "Error: Required GNU $name, try \`brew install $brew_name\`"
+    exit 1
+  fi
 }
 check_command_installed brew brew
 check_command_installed zbarimg zbarimg
 check_command_installed pngpaste pngpaste
-
 
 pngpaste /tmp/a.png && zbarimg /tmp/a.png
diff --git a/local/bin/remark b/local/bin/remark
--- a/local/bin/remark
+++ b/local/bin/remark
@@ -2,39 +2,38 @@
 
 # render markdown file with remark https://github.com/gnab/remark
 
-
-if [ `uname` = 'Darwin' ]; then
-	SED_BIN="gsed"
-elif [ `uname -s` = 'Linux' ] || [ `uname -o` = 'Cygwin' ]; then
-	SED_BIN="sed"
+if [ $(uname) = 'Darwin' ]; then
+  SED_BIN="gsed"
+elif [ $(uname -s) = 'Linux' ] || [ $(uname -o) = 'Cygwin' ]; then
+  SED_BIN="sed"
 fi
 
 FILE_NAME=$1
 
 if [ ! -f $FILE_NAME ]; then
-	echo "warnning: $FILE_NAME not exist!"
-	echo ''
-	echo 'Usage:'
-	echo 'remark example.md'
-	exit 0;
+  echo "warnning: $FILE_NAME not exist!"
+  echo ''
+  echo 'Usage:'
+  echo 'remark example.md'
+  exit 0
 fi
 
 OUTPUT_FILE_NAME=$FILE_NAME.remark.generated.html
 
-check_command_installed () {
-	NAME=$1
-	BREW_NAME=$2
-	if ! [ -x "$(command -v $NAME)" ]; then
-		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
-		exit 1;
-	fi
+check_command_installed() {
+  NAME=$1
+  BREW_NAME=$2
+  if ! [ -x "$(command -v $NAME)" ]; then
+    echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+    exit 1
+  fi
 }
 
-if [ `uname` = 'Darwin' ]; then
-	check_command_installed gsed gnu-sed
+if [ $(uname) = 'Darwin' ]; then
+  check_command_installed gsed gnu-sed
 fi
 
-cat > $OUTPUT_FILE_NAME << EOF
+cat >$OUTPUT_FILE_NAME <<EOF
 <!DOCTYPE html>
 <html>
   <head>
@@ -56,9 +55,9 @@ cat > $OUTPUT_FILE_NAME << EOF
 
 EOF
 
-cat $FILE_NAME | $SED_BIN 's/^##/---\n\n#/g' | $SED_BIN -E 's/^(!\[.+\]\(.+\))$/\n\n---\n\n\1\n\n---\n\n/g'  >> $OUTPUT_FILE_NAME
+cat $FILE_NAME | $SED_BIN 's/^##/---\n\n#/g' | $SED_BIN -E 's/^(!\[.+\]\(.+\))$/\n\n---\n\n\1\n\n---\n\n/g' >>$OUTPUT_FILE_NAME
 
-cat >> $OUTPUT_FILE_NAME << EOF
+cat >>$OUTPUT_FILE_NAME <<EOF
 
     </textarea>
     <script src="https://cdn.staticfile.org/remark/0.14.0/remark.min.js"></script>
@@ -76,6 +75,5 @@ cat >> $OUTPUT_FILE_NAME << EOF
 EOF
 
 echo "Generate $OUTPUT_FILE_NAME successful."
-
 
 #vim: set expandtab:
