refactor: movie to gif

diff --git a/local/bin/mov2gif b/local/bin/mov2gif
--- a/local/bin/mov2gif
+++ b/local/bin/mov2gif
@@ -2,9 +2,32 @@
 # By: Hua Liang [Stupid ET]
 # Website: http://EverET.org
 # brew install ffmpeg imagemagick gifsicle
-#
+
+
+check_command_installed() {
+  name=$1
+  brew_name=$2
+  if ! [ -x "$(command -v $name)" ]; then
+    echo "Error: Required GNU $name, try \`brew install $brew_name\`"
+    exit 1
+  fi
+}
+
+check_command_installed ffmpeg ffmpeg
+check_command_installed convert imagemagick
+check_command_installed gifsicle gifsicle
 
 mov_file=$1
 gif_file=$2
+
+if [ -z "$mov_file" ]; then
+  echo "Useage: mov2gif mov_file gif_file"
+  exit 0
+fi
+
+if [ -z "$gif_file" ]; then
+  echo "Useage: mov2gif mov_file gif_file"
+  exit 0
+fi
 
 ffmpeg -i $mov_file -r 10 -f image2pipe -vcodec ppm - | convert -verbose +dither -layers Optimize -resize 640x640\> - gif:- | gifsicle --colors 128 --delay=5 --loop --optimize=3 --multifile - >$gif_file
