style: format

diff --git a/local/bin/reduceimg b/local/bin/reduceimg
--- a/local/bin/reduceimg
+++ b/local/bin/reduceimg
@@ -5,21 +5,20 @@ set -e
 
 file_name=$1
 
-check_command_installed () {
-	name=$1
-	brew_name=$2
-	if ! [ -x "$(command -v $name)" ]; then
-		echo "Error: Required GNU $name, try \`brew install $brew_name\`"
-		exit 1;
-	fi
+check_command_installed() {
+  name=$1
+  brew_name=$2
+  if ! [ -x "$(command -v $name)" ]; then
+    echo "Error: Required GNU $name, try \`brew install $brew_name\`"
+    exit 1
+  fi
 }
 
 if [ -z "$file_name" ]; then
-	echo "Useage: tinypng filename"
-	exit 0;
+  echo "Useage: tinypng filename"
+  exit 0
 fi
 check_command_installed mogrify imagemagic
-
 
 cp "$file_name" "$file_name.original"
 mogrify -resize '1200x1200' $f
diff --git a/local/bin/reveal b/local/bin/reveal
--- a/local/bin/reveal
+++ b/local/bin/reveal
@@ -2,39 +2,38 @@
 
 # render markdown file with reveal https://github.com/hakimel/reveal.js#markdown
 
-
-if [ `uname` = 'Darwin' ]; then
-	SED_BIN="gsed"
-elif [ `uname -s` = 'Linux' ] || [ `uname -o` = 'Cygwin' ]; then
-	SED_BIN="sed"
+if [ $(uname) = 'Darwin' ]; then
+  SED_BIN="gsed"
+elif [ $(uname -s) = 'Linux' ] || [ $(uname -o) = 'Cygwin' ]; then
+  SED_BIN="sed"
 fi
 
 FILE_NAME=$1
 
 if [ ! -f $FILE_NAME ]; then
-	echo "warnning: $FILE_NAME not exist!"
-	echo ''
-	echo 'Usage:'
-	echo 'reveal example.md'
-	exit 0;
+  echo "warnning: $FILE_NAME not exist!"
+  echo ''
+  echo 'Usage:'
+  echo 'reveal example.md'
+  exit 0
 fi
 
-check_command_installed () {
-	NAME=$1
-	BREW_NAME=$2
-	if ! [ -x "$(command -v $NAME)" ]; then
-		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
-		exit 1;
-	fi
+check_command_installed() {
+  NAME=$1
+  BREW_NAME=$2
+  if ! [ -x "$(command -v $NAME)" ]; then
+    echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+    exit 1
+  fi
 }
 
 OUTPUT_FILE_NAME=$FILE_NAME.reveal.generated.html
 
-if [ `uname` = 'Darwin' ]; then
-	check_command_installed gsed gnu-sed
+if [ $(uname) = 'Darwin' ]; then
+  check_command_installed gsed gnu-sed
 fi
 
-cat > $OUTPUT_FILE_NAME << EOF
+cat >$OUTPUT_FILE_NAME <<EOF
 <!doctype html>
 <html>
 	<head>
@@ -71,22 +70,21 @@ cat > $OUTPUT_FILE_NAME << EOF
 
 EOF
 
-cat >> $OUTPUT_FILE_NAME << EOF
+cat >>$OUTPUT_FILE_NAME <<EOF
 				<section data-markdown>
 					<textarea data-template>
 EOF
 
-cat $FILE_NAME | \
-	$SED_BIN -E 's/^(\* +.*)$/\1<!-- .element: class="fragment" -->/g' | \
-	$SED_BIN 's/^##/				<\/textarea>\n				<\/section>\n				<section data-markdown>\n					<textarea data-template>\n##/g'  >> $OUTPUT_FILE_NAME
+cat $FILE_NAME |
+  $SED_BIN -E 's/^(\* +.*)$/\1<!-- .element: class="fragment" -->/g' |
+  $SED_BIN 's/^##/				<\/textarea>\n				<\/section>\n				<section data-markdown>\n					<textarea data-template>\n##/g' >>$OUTPUT_FILE_NAME
 
-
-cat >> $OUTPUT_FILE_NAME << EOF
+cat >>$OUTPUT_FILE_NAME <<EOF
 					</textarea>
 				</section>
 EOF
 
-cat >> $OUTPUT_FILE_NAME << EOF
+cat >>$OUTPUT_FILE_NAME <<EOF
 			</div>
 		</div>
 
@@ -113,6 +111,5 @@ cat >> $OUTPUT_FILE_NAME << EOF
 EOF
 
 echo "Generate $OUTPUT_FILE_NAME successful."
-
 
 #vim: set expandtab:
diff --git a/local/bin/svg2icns b/local/bin/svg2icns
--- a/local/bin/svg2icns
+++ b/local/bin/svg2icns
@@ -9,7 +9,6 @@
 ###   <https://developer.apple.com/library/content/documentation/GraphicsAnimation/Conceptual/HighResolutionOSX/Optimizing/Optimizing.html>
 ###
 
-
 script="$(basename $0 .bash)"
 
 : ${MAGICK_HOME?Requires ImageMagick to be installed}
@@ -18,60 +17,55 @@ CONVERT_BIN="convert"
 
 ## Usage function
 usage() {
-    cat <<END_USAGE >&2
+  cat <<END_USAGE >&2
 Usage: ${script} <svgfilename> [<icnsfilename>]
   svgfilename:  input file in SVG format
   icnsfilename: output file in ICNS format (optional)
 
 END_USAGE
 }
- 
+
 ## Call usage() function if args not supplied
 argc="$#"
-if [[ "$argc" -lt 1 ]] || [[ "$argc" -gt 2 ]];
-then
-    usage
-    exit 1
+if [[ "$argc" -lt 1 ]] || [[ "$argc" -gt 2 ]]; then
+  usage
+  exit 1
 fi
 
 ## Verify first positional argument
 svgfilename="$1"
-if [ ! -f "${svgfilename}" ];
-then
-    usage
-    echo "${script}: no such file: ${svgfilename}" >&2
-    exit 1
+if [ ! -f "${svgfilename}" ]; then
+  usage
+  echo "${script}: no such file: ${svgfilename}" >&2
+  exit 1
 else
-    echo -n ''
-    # ## Verify scalable vector graphics file
-    # $(file "${svgfilename}" | cut -d':' -f2- | grep -qs 'SVG')
-    # if [ "$?" -ne 0 ];
-    # then
-        # usage
-        # echo "${script}: SVG file required: ${svgfilename}" >&2
-        # exit 1
-    # fi
+  echo -n ''
+  # ## Verify scalable vector graphics file
+  # $(file "${svgfilename}" | cut -d':' -f2- | grep -qs 'SVG')
+  # if [ "$?" -ne 0 ];
+  # then
+  # usage
+  # echo "${script}: SVG file required: ${svgfilename}" >&2
+  # exit 1
+  # fi
 fi
 
 ## Verify second positional argument if given
-if [ "$argc" -eq 2 ];
-then
-    icnsfilename="$2"
-    if [ -n "${icnsfilename}" ];
-    then
-        ## Ensure file extension
-        ext=${icnsfilename##*.}
-        if [ "$ext" != "icns" ];
-        then
-            icnsfilename="${icnsfilename}.icns"
-        fi
-    else
-        ## Given empty string as second arg
-        icnsfilename="${svgfilename%.*}.icns"
+if [ "$argc" -eq 2 ]; then
+  icnsfilename="$2"
+  if [ -n "${icnsfilename}" ]; then
+    ## Ensure file extension
+    ext=${icnsfilename##*.}
+    if [ "$ext" != "icns" ]; then
+      icnsfilename="${icnsfilename}.icns"
     fi
-else
-    ## No second arg
+  else
+    ## Given empty string as second arg
     icnsfilename="${svgfilename%.*}.icns"
+  fi
+else
+  ## No second arg
+  icnsfilename="${svgfilename%.*}.icns"
 fi
 
 ## Create iconset directory if necessary
@@ -94,49 +88,44 @@ mkdir -p "${iconsetdirname}"
 ##+---------------------+--------------------+--------------+
 
 ## Create PNG files as described in table
-sizes=( 16 32 128 256 512 )
-densities=( 72 144 )
+sizes=(16 32 128 256 512)
+densities=(72 144)
 
-for size in "${sizes[@]}"
-do
-    dimen="${size}x${size}"
-    for density in "${densities[@]}"
-    do
-        if [ "${density}" == "72" ];
-        then
-            ## std
-            resolution="${dimen}"
-            scale=""
-        else
-            ## hires
-            resolution="$(( $size * 2 ))x$(( $size * 2 ))"
-            scale="@2x"
-        fi
-        pngfilename="${iconsetdirname}/icon_${dimen}${scale}.png"
-        #echo \
-        ${CONVERT_BIN} \
-           -background "none" \
-           -density "${density}" \
-           -resize "${resolution}!" \
-           -units "PixelsPerInch" \
-           "${svgfilename}" \
-           "${pngfilename}"
-        if [ "$?" -ne 0 ];
-        then
-            echo "${script}: error creating icon file: ${pngfilename}" >&2
-            exit 1
-        fi
-    done
+for size in "${sizes[@]}"; do
+  dimen="${size}x${size}"
+  for density in "${densities[@]}"; do
+    if [ "${density}" == "72" ]; then
+      ## std
+      resolution="${dimen}"
+      scale=""
+    else
+      ## hires
+      resolution="$(($size * 2))x$(($size * 2))"
+      scale="@2x"
+    fi
+    pngfilename="${iconsetdirname}/icon_${dimen}${scale}.png"
+    #echo \
+    ${CONVERT_BIN} \
+      -background "none" \
+      -density "${density}" \
+      -resize "${resolution}!" \
+      -units "PixelsPerInch" \
+      "${svgfilename}" \
+      "${pngfilename}"
+    if [ "$?" -ne 0 ]; then
+      echo "${script}: error creating icon file: ${pngfilename}" >&2
+      exit 1
+    fi
+  done
 done
 
 ## Convert iconset to ICNS file
 iconutil --convert icns "${iconsetdirname}"
-if [ "$?" -ne 0 ];
-then
-    echo "${script}: error converting iconset to ICNS: ${iconsetdirname}" >&2
-    exit 1
+if [ "$?" -ne 0 ]; then
+  echo "${script}: error converting iconset to ICNS: ${iconsetdirname}" >&2
+  exit 1
 else
-    rm -rf "${iconsetdirname}"
+  rm -rf "${iconsetdirname}"
 fi
 
 exit 0
diff --git a/local/bin/tinypng b/local/bin/tinypng
--- a/local/bin/tinypng
+++ b/local/bin/tinypng
@@ -7,21 +7,20 @@ file_name=$1
 export http_proxy=http://127.0.0.1:1235
 export https_proxy=http://127.0.0.1:1235
 
-check_command_installed () {
-	name=$1
-	brew_name=$2
-	if ! [ -x "$(command -v $name)" ]; then
-		echo "Error: Required GNU $name, try \`brew install $brew_name\`"
-		exit 1;
-	fi
+check_command_installed() {
+  name=$1
+  brew_name=$2
+  if ! [ -x "$(command -v $name)" ]; then
+    echo "Error: Required GNU $name, try \`brew install $brew_name\`"
+    exit 1
+  fi
 }
 
 if [ -z "$file_name" ]; then
-	echo "Useage: tinypng filename"
-	exit 0;
+  echo "Useage: tinypng filename"
+  exit 0
 fi
 check_command_installed jq jq
-
 
 cp "$file_name" "$file_name.original"
 url=$(curl -s --user "api:${TINYPNG_API_SECRECT}" --data-binary "@$file_name" https://api.tinify.com/shrink | jq -r ".output.url")
