refact: tinypng

diff --git a/local/bin/tinypng b/local/bin/tinypng
--- a/local/bin/tinypng
+++ b/local/bin/tinypng
@@ -1,28 +1,30 @@
 #!/bin/sh
 
-FILE_NAME=$1
+set -e
+
+file_name=$1
 
 export http_proxy=http://127.0.0.1:1235
 export https_proxy=http://127.0.0.1:1235
 
 check_command_installed () {
-	NAME=$1
-	BREW_NAME=$2
-	if ! [ -x "$(command -v $NAME)" ]; then
-		echo "Error: Required GNU $NAME, try \`brew install $BREW_NAME\`"
+	name=$1
+	brew_name=$2
+	if ! [ -x "$(command -v $name)" ]; then
+		echo "Error: Required GNU $name, try \`brew install $brew_name\`"
 		exit 1;
 	fi
 }
 
-if [ -z $FILE_NAME ]; then
+if [ -z "$file_name" ]; then
 	echo "Useage: tinypng filename"
 	exit 0;
 fi
 check_command_installed jq jq
 
 
-cp $FILE_NAME ${FILE_NAME}.bak
-URL=$(curl --user api:${TINYPNG_API_SECRECT} --data-binary @$FILE_NAME https://api.tinify.com/shrink | jq -r '.output.url')
-wget $URL -O $FILE_NAME
+cp "$file_name" "$file_name.original"
+url=$(curl -s --user "api:${TINYPNG_API_SECRECT}" --data-binary "@$file_name" https://api.tinify.com/shrink | jq -r ".output.url")
+wget $url -O "$file_name"
 
 # vim: set ft=sh:
